model:
  name: "monai_unet_3d"
  spatial_dims: 3
  in_channels: 1
  out_channels: 2  # background vs sinus/mucosa (adjust when you add more labels)
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]

training:
  patch_size: [96, 96, 96]
  batch_size: 2
  max_epochs: 200
  learning_rate: 1.0e-4
  optimizer: "adam"
  loss: "dice_ce"
  roi_foreground_ratio: 0.5

data:
  dataset_root: "data/datasets/open_sinus"
  train_split: "train.json"
  val_split: "val.json"
  cache_rate: 0.6
  transforms:
    - name: LoadImaged
      keys: ["image", "mask"]
    - name: EnsureChannelFirstd
      keys: ["image", "mask"]
    - name: Spacingd
      keys: ["image", "mask"]
      pixdim: [1.0, 1.0, 1.0]
      mode: ["bilinear", "nearest"]
    - name: ScaleIntensityRanged
      keys: ["image"]
      a_min: -1000
      a_max: 200
      b_min: 0.0
      b_max: 1.0
    - name: RandSpatialCropd
      keys: ["image", "mask"]
      roi_size: [96, 96, 96]
      random_center: true
      random_size: false
    - name: RandFlipd
      keys: ["image", "mask"]
      prob: 0.5
      spatial_axis: 0
    - name: RandRotate90d
      keys: ["image", "mask"]
      prob: 0.5
